export type ReportAmenity = { type: string; detail: string; latitude?: number; longitude?: number };
export type ReportResearch = { type: string; locationLabel: string; generatedAt: string; summary: string; caveats: string; sources: { label: string; url: string; retrievedAt: string; coverage: string; period?: string }[] };
export type ReportSnapshot = { amenities?: ReportAmenity[]; serviceStatus?: { label?: string; asOf?: string }; research?: ReportResearch[] };
type ReportCrime = { label: string; geographicScope: string; generatedAt: string; summary: string; caveats: string; presentation: string; sources: ReportResearch["sources"] };

export function readReportSnapshot(snapshot: unknown): ReportSnapshot | null {
  if (!snapshot || typeof snapshot !== "object") return null;
  const candidate = snapshot as Record<string, unknown>;
  const amenities = Array.isArray(candidate.amenities) ? candidate.amenities.filter((item): item is ReportAmenity => Boolean(item) && typeof item === "object" && typeof (item as Record<string, unknown>).type === "string" && typeof (item as Record<string, unknown>).detail === "string").map(item => ({ type: item.type, detail: item.detail, ...(typeof item.latitude === "number" && typeof item.longitude === "number" ? { latitude: item.latitude, longitude: item.longitude } : {}) })) : undefined;
  const service = candidate.serviceStatus;
  const serviceStatus = service && typeof service === "object" ? { label: typeof (service as Record<string, unknown>).label === "string" ? (service as Record<string, unknown>).label as string : undefined, asOf: typeof (service as Record<string, unknown>).asOf === "string" ? (service as Record<string, unknown>).asOf as string : undefined } : undefined;
  const readSources = (value: unknown): ReportResearch["sources"] => Array.isArray(value) ? value.filter((source): source is ReportResearch["sources"][number] => Boolean(source) && typeof source === "object" && typeof (source as Record<string, unknown>).label === "string" && typeof (source as Record<string, unknown>).url === "string" && typeof (source as Record<string, unknown>).retrievedAt === "string" && typeof (source as Record<string, unknown>).coverage === "string") : [];
  const reviewedResearch = Array.isArray(candidate.research) ? candidate.research.filter((item): item is ReportResearch => Boolean(item) && typeof item === "object" && typeof (item as Record<string, unknown>).type === "string" && typeof (item as Record<string, unknown>).locationLabel === "string" && typeof (item as Record<string, unknown>).generatedAt === "string" && typeof (item as Record<string, unknown>).summary === "string" && typeof (item as Record<string, unknown>).caveats === "string").map(item => ({ ...item, sources: readSources(item.sources) })).filter(item => item.type !== "crime") : [];
  const crimeEvidence = Array.isArray(candidate.crime) ? candidate.crime.filter((item): item is ReportCrime => Boolean(item) && typeof item === "object" && typeof (item as Record<string, unknown>).label === "string" && typeof (item as Record<string, unknown>).geographicScope === "string" && typeof (item as Record<string, unknown>).generatedAt === "string" && typeof (item as Record<string, unknown>).summary === "string" && typeof (item as Record<string, unknown>).caveats === "string" && typeof (item as Record<string, unknown>).presentation === "string").map(item => ({ type: "Crime context", locationLabel: item.geographicScope, generatedAt: item.generatedAt, summary: item.summary, caveats: `${item.caveats} ${item.presentation}`, sources: readSources(item.sources) })) : [];
  return { amenities, serviceStatus, research: [...reviewedResearch, ...crimeEvidence] };
}
