import { Button } from "@/components/ui/button";
import { PublicFooter, PublicHeader } from "@/components/PublicShell";
import { startLogin } from "@/const";
import { ArrowRight, BadgeCheck, Building2, ChartNoAxesCombined, ChevronRight, CircleCheck, FileText, House, MapPinned, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { useEffect } from "react";
import { Link } from "wouter";

/**
 * All content in this page are only for example, replace with your own feature implementation
 * When building pages, remember your instructions in Frontend Workflow, Frontend Best Practices, Design Guide and Common Pitfalls
 */
export default function Home() {
  useEffect(() => { document.title = "Amarktai Property | Clearer property decisions"; let description = document.querySelector('meta[name="description"]') as HTMLMetaElement | null; if (!description) { description = document.createElement("meta"); description.name = "description"; document.head.appendChild(description); } description.content = "Amarktai Property connects listings, buyer intelligence, building operations, and controlled sharing in one South African property platform."; }, []);
  return (
    <div className="min-h-screen overflow-hidden bg-[#faf9f6]">
      <PublicHeader overlay />

      <section id="public-main" tabIndex={-1} className="relative min-h-[720px] bg-[#17314e] pt-28 text-white">
        <div className="absolute inset-0"><img src="/manus-storage/amarktai-hero-home_e4e9ca03.jpg" alt="Contemporary South African home at dusk" className="size-full object-cover opacity-55" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(12,31,50,.94)_0%,rgba(17,43,66,.78)_42%,rgba(17,43,66,.24)_100%)]" /></div>
        <div className="container relative grid items-end gap-12 pb-16 pt-24 lg:grid-cols-[1.05fr_.95fr] lg:pb-20">
          <div className="max-w-2xl"><p className="eyebrow text-[#e5bf78]">A more considered property platform</p><h1 className="font-editorial mt-5 text-5xl leading-[.98] tracking-tight sm:text-6xl lg:text-7xl">Every property has a story. Make it <em className="text-[#e6bd73]">clearer.</em></h1><p className="mt-7 max-w-xl text-base leading-7 text-white/76 sm:text-lg">Amarktai Property gives agents, managers and buyers one calm, intelligent place to market homes, understand neighbourhoods and keep buildings moving.</p><div className="mt-9 flex flex-wrap gap-3"><Button onClick={() => startLogin()} size="lg" className="rounded-full bg-[#d9a856] px-6 text-[#1b3046] hover:bg-[#efc47d]">Enter the workspace <ArrowRight className="ml-2 size-4" /></Button><Link href="/report/preview" className="inline-flex items-center rounded-full border border-white/35 px-6 text-sm font-semibold transition-colors hover:bg-white/10">Explore a buyer report <ChevronRight className="ml-1 size-4" /></Link></div><div className="mt-12 flex flex-wrap gap-x-7 gap-y-3 text-xs text-white/70"><span className="flex items-center gap-2"><CircleCheck className="size-4 text-[#e6bd73]" /> Source-aware reporting</span><span className="flex items-center gap-2"><CircleCheck className="size-4 text-[#e6bd73]" /> Controlled sharing</span><span className="flex items-center gap-2"><CircleCheck className="size-4 text-[#e6bd73]" /> South African context</span></div></div>
          <div className="glass-panel ml-auto max-w-md rounded-[1.4rem] p-5 shadow-2xl"><div className="flex items-center justify-between border-b border-white/15 pb-4"><div><p className="text-xs font-medium text-white/55">Amarktai intelligence brief</p><p className="mt-1 font-editorial text-xl">A report that earns trust</p></div><span className="rounded-full bg-[#e5bf78]/15 px-3 py-1 text-xs font-semibold text-[#f4d79f]">Preview</span></div><div className="map-grid relative mt-4 h-48 overflow-hidden rounded-xl border border-white/10"><div className="absolute left-[48%] top-[38%] grid size-10 place-items-center rounded-full border-4 border-white bg-[#d9a856] shadow-lg"><House className="size-4 text-[#18324f]" /></div><div className="absolute bottom-3 left-3 rounded-lg bg-[#17314e]/90 px-3 py-2 text-xs">5 amenity categories<br /><span className="text-white/55">Source-labelled & dated</span></div></div><div className="mt-4 grid grid-cols-3 gap-2"><MiniMetric icon={<MapPinned className="size-4" />} label="Amenities" value="Nearby" /><MiniMetric icon={<ShieldCheck className="size-4" />} label="Safety data" value="Dated" /><MiniMetric icon={<FileText className="size-4" />} label="Report" value="Shareable" /></div></div>
        </div>
      </section>

      <section id="platform" className="container py-24"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">One connected operating system</p><h2 className="font-editorial mt-4 text-4xl leading-tight text-[#193552] sm:text-5xl">Built for the people who make property work.</h2><p className="mt-5 max-w-sm leading-7 text-slate-600">Not a generic portal. A deliberate workspace for the work before, around and after a property is listed.</p></div><div className="grid gap-4 sm:grid-cols-2"><Feature icon={<House />} title="Sales workspace" copy="Listings, leads, viewings and tasks designed around a better buyer journey." /><Feature icon={<MapPinned />} title="Buyer intelligence" copy="Amenity layers, dated data and source context—never an unexplained score." /><Feature icon={<Building2 />} title="Building operations" copy="Maintenance, notices, documents and unit-level workflows in one calm place." /><Feature icon={<Sparkles />} title="GenX studio" copy="Capability-verified media jobs with status, cost and credit controls." /></div></div></section>

      <section id="intelligence" className="bg-[#eaf0ed] py-24"><div className="container grid gap-10 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div className="map-grid relative min-h-[440px] overflow-hidden rounded-[1.6rem] border border-[#d7e0d9] p-6"><div className="absolute left-[42%] top-[42%] grid size-14 place-items-center rounded-full border-[6px] border-white bg-[#1a3857] shadow-xl"><House className="size-5 text-[#e6bd73]" /></div><div className="absolute left-6 top-6 rounded-xl bg-white/95 p-4 shadow-lg"><p className="text-xs font-bold uppercase tracking-widest text-[#b68238]">Neighbourhood context</p><p className="mt-1 font-editorial text-xl text-[#193552]">See the whole setting</p></div><div className="absolute bottom-6 right-6 grid gap-2"><MapChip label="Schools" color="bg-[#337f88]" /><MapChip label="Healthcare" color="bg-[#ad6152]" /><MapChip label="Transport" color="bg-[#b68238]" /></div></div><div><p className="eyebrow">Buyer reports that show their work</p><h2 className="font-editorial mt-4 text-4xl leading-tight text-[#193552] sm:text-5xl">Intelligence with a provenance trail.</h2><p className="mt-5 max-w-xl leading-7 text-slate-600">Every report makes the source, date and coverage visible. Cached amenity layers keep the experience quick; crime and service data remain carefully labelled rather than overstated.</p><div className="mt-7 space-y-4"><ReportPoint icon={<BadgeCheck className="size-5" />} title="Controlled by design" copy="Share only the property or report view you intend, with an expiry and revoke control." /><ReportPoint icon={<ShieldCheck className="size-5" />} title="Evidence, not a verdict" copy="Source-labelled information equips a buyer without declaring an area safe, unsafe or certain." /></div><Link href="/report/preview" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-[#193552] underline decoration-[#d9a856] decoration-2 underline-offset-4">Open buyer report preview <ArrowRight className="size-4" /></Link></div></div></section>

      <section id="pricing" className="container py-24"><div className="text-center"><p className="eyebrow">Simple, agency-ready plans</p><h2 className="font-editorial mt-4 text-4xl text-[#193552] sm:text-5xl">Choose the operating room you need.</h2></div><div className="mx-auto mt-12 grid max-w-5xl gap-4 md:grid-cols-3"><PriceCard name="Starter" price="R0" note="for your first workspace" items={["Branded workspace", "Core listings & reports", "Building operations"]} /><PriceCard featured name="Professional" price="R499" note="per organisation / month" items={["Everything in Starter", "GenX media credits", "Team roles & exports"]} /><PriceCard name="Enterprise" price="Enterprise" note="for scaled agencies" items={["Advanced permissions", "Approved portal adapters", "Custom onboarding"]} /></div><p className="mx-auto mt-6 max-w-3xl text-center text-xs leading-5 text-slate-500">Payment entitlements are activated only after server-side PayFast ITN verification. Provider and portal capabilities remain configuration-gated.</p></section>

      <section id="trust" className="bg-[#17314e] py-20 text-white"><div className="container grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow text-[#e5bf78]">Designed for trust</p><h2 className="font-editorial mt-4 text-4xl leading-tight">Sophisticated where it matters. Explicit where it counts.</h2></div><div className="grid gap-4 sm:grid-cols-3"><TrustCard icon={<ShieldCheck />} title="Private by default" copy="Organisation boundaries and scoped resident access are part of the data model." /><TrustCard icon={<FileText />} title="Auditable actions" copy="Sharing, exports, payments and operational work can be recorded as events." /><TrustCard icon={<UsersRound />} title="Human control" copy="No unapproved portal posting, no mystery area scores, no silent payment unlocks." /></div></div></section>
      <PublicFooter />
    </div>
  );
}

function MiniMetric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="rounded-lg bg-white/10 p-3"><div className="text-[#e6bd73]">{icon}</div><p className="mt-2 text-[11px] text-white/55">{label}</p><p className="text-sm font-semibold">{value}</p></div>; }
function Feature({ icon, title, copy }: { icon: React.ReactNode; title: string; copy: string }) { return <div className="soft-card p-6"><div className="grid size-10 place-items-center rounded-xl bg-[#edf2f1] text-[#193552]">{icon}</div><h3 className="mt-5 text-lg font-bold text-[#193552]">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{copy}</p></div>; }
function ReportPoint({ icon, title, copy }: { icon: React.ReactNode; title: string; copy: string }) { return <div className="flex gap-4"><span className="mt-0.5 text-[#b68238]">{icon}</span><div><h3 className="font-bold text-[#193552]">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{copy}</p></div></div>; }
function MapChip({ label, color }: { label: string; color: string }) { return <div className="flex items-center gap-2 rounded-lg bg-white/95 px-3 py-2 text-xs font-semibold text-[#193552] shadow-lg"><span className={`size-2 rounded-full ${color}`} />{label}</div>; }
function PriceCard({ name, price, note, items, featured }: { name: string; price: string; note: string; items: string[]; featured?: boolean }) { return <div className={`rounded-[1.2rem] border p-6 ${featured ? "border-[#c38b3d] bg-[#193552] text-white shadow-xl" : "border-[#e7e1d8] bg-white text-[#193552]"}`}><p className="text-sm font-bold">{name}</p><p className="font-editorial mt-4 text-4xl">{price}<span className="font-sans text-sm font-normal opacity-60">{price !== "Enterprise" && "/mo"}</span></p><p className={`mt-1 text-sm ${featured ? "text-white/65" : "text-slate-500"}`}>{note}</p><div className={`my-6 h-px ${featured ? "bg-white/15" : "bg-[#e7e1d8]"}`} />{items.map(item => <p key={item} className={`mb-3 flex gap-2 text-sm ${featured ? "text-white/85" : "text-slate-600"}`}><CircleCheck className={`size-4 ${featured ? "text-[#e6bd73]" : "text-[#b68238]"}`} />{item}</p>)}<Button onClick={() => startLogin()} className={`mt-5 w-full rounded-full ${featured ? "bg-[#d9a856] text-[#193552] hover:bg-[#e6bd73]" : "bg-[#edf2f1] text-[#193552] hover:bg-[#e6e4de]"}`}>{name === "Enterprise" ? "Explore enterprise" : "Get started"}</Button></div>; }
function TrustCard({ icon, title, copy }: { icon: React.ReactNode; title: string; copy: string }) { return <div className="rounded-xl border border-white/10 bg-white/5 p-5"><div className="text-[#e6bd73]">{icon}</div><h3 className="mt-4 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-white/60">{copy}</p></div>; }
