import { PublicFooter, PublicHeader } from "@/components/PublicShell";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { ArrowRight, ShieldCheck } from "lucide-react";
import { useEffect } from "react";
import { Link, useLocation } from "wouter";

const content = {
  "/privacy": { eyebrow: "Privacy", title: "A deliberate approach to property data.", intro: "Amarktai Property is designed to separate organisations, scope resident access, and keep controlled-share links revocable.", sections: [["What we process", "Account details, listing data, operational records and authorised payment references are processed to provide the workspace. Sensitive credentials stay server-side."], ["How access works", "Organisation memberships and property-share tokens determine access. A share can expire or be revoked by its issuer."], ["Your controls", "Agency owners can manage team access. Building users see only the information explicitly scoped to their role and property context."]] },
  "/terms": { eyebrow: "Terms of use", title: "Clarity for every participant.", intro: "Amarktai Property provides sales, intelligence and operational tools; it does not replace legal, financial, accounting or safety advice.", sections: [["Buyer intelligence", "Amenity, crime and service information must be read with its source, scope and reporting date. The platform does not issue safety or investment verdicts."], ["Authorised publishing", "Portal exports and integrations are used only where written technical approval and credentials are provided. Unauthorised posting and scraping are not permitted."], ["Account responsibilities", "Users are responsible for the listing facts, consent and materials they add, and for reviewing any provider-generated media before sharing it."]] },
  "/trust": { eyebrow: "Trust & safety", title: "The platform prefers evidence over automation theatre.", intro: "Amarktai Property uses explicit safeguards around source data, payments, media and controlled sharing.", sections: [["Payment protection", "Entitlements are granted only after a server-side PayFast notification verifies the order reference, amount and signature."], ["Generative media", "GenX media jobs remain unavailable until verified deployment configuration is present. Job state, retry count and credit use are tracked."], ["Operational records", "Audit-ready events support accountability for property shares, exports, media requests and sensitive operational changes."]] },
};

export default function Legal() { const [location] = useLocation(); const page = content[location as keyof typeof content] ?? content["/privacy"]; useEffect(() => { document.title = `${page.eyebrow} | Amarktai Property`; let description = document.querySelector('meta[name="description"]') as HTMLMetaElement | null; if (!description) { description = document.createElement("meta"); description.name = "description"; document.head.appendChild(description); } description.content = page.intro; }, [page]); return <div className="min-h-screen bg-[#f8f8f5]"><PublicHeader /><main id="public-main" tabIndex={-1} className="container max-w-4xl py-16"><p className="eyebrow">{page.eyebrow}</p><h1 className="font-editorial mt-4 text-5xl leading-tight text-[#193552]">{page.title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-600">{page.intro}</p><div className="mt-10 space-y-4">{page.sections.map(([heading, copy]) => <section key={heading} className="soft-card p-6"><div className="flex gap-3"><ShieldCheck className="mt-1 size-5 shrink-0 text-[#b68238]" /><div><h2 className="text-lg font-bold text-[#193552]">{heading}</h2><p className="mt-2 leading-7 text-slate-600">{copy}</p></div></div></section>)}</div><section className="mt-12 rounded-[1.25rem] bg-[#193552] p-7 text-white"><p className="eyebrow text-[#e5bf78]">Continue with clarity</p><h2 className="font-editorial mt-3 text-3xl">Explore the property experience on your terms.</h2><div className="mt-6 flex flex-wrap gap-3"><Link href="/report/preview" className="inline-flex items-center rounded-full bg-[#d9a856] px-5 py-3 text-sm font-bold text-[#193552] hover:bg-[#efc47d]">Buyer report preview<ArrowRight className="ml-2 size-4" /></Link><Button onClick={() => startLogin()} variant="outline" className="rounded-full border-white/30 text-white hover:bg-white/10 hover:text-white">Enter the workspace</Button></div></section></main><PublicFooter /></div>; }
