import { PublicFooter, PublicHeader } from "@/components/PublicShell";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { ArrowRight, BadgeCheck, Building2, ChartNoAxesCombined, FileCheck2, House, LockKeyhole, MapPinned, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { useEffect } from "react";
import { Link, useLocation } from "wouter";

type PageDefinition = { eyebrow: string; title: string; accent: string; description: string; primary: string; cards: { icon: React.ReactNode; title: string; copy: string }[]; note: string };

const pages: Record<string, PageDefinition> = {
  "/platform": { eyebrow: "The Amarktai operating system", title: "One calm place for every moment around a property.", accent: "Align sales, intelligence and operations", description: "Amarktai gives property teams a shared operating picture—from a first listing brief to a controlled buyer report and the day-to-day work of a complex.", primary: "Enter the workspace", cards: [{ icon: <House />, title: "Listing command centre", copy: "Structure the details, media, status and controlled share paths that make a listing ready." }, { icon: <UsersRound />, title: "Relationship work", copy: "Capture buyer leads, viewings and follow-up actions in the organisation that owns the work." }, { icon: <Building2 />, title: "Operational continuity", copy: "Coordinate buildings, notices, documents, maintenance and scoped resident workflows." }], note: "Built around explicit roles, active organisation context, and records that remain attributable." },
  "/buyers": { eyebrow: "For buyers", title: "A more complete way to understand a home.", accent: "Evidence that remains visible", description: "A buyer report gives the property its setting: available amenity context, dated source information, and a controlled route back to the agent who shared it.", primary: "Explore a buyer report", cards: [{ icon: <MapPinned />, title: "Location in context", copy: "Place-aware information is presented alongside the home instead of buried in a generic listing." }, { icon: <FileCheck2 />, title: "Provenance trail", copy: "Every live report is designed to show its source and date, not hide uncertainty behind a score." }, { icon: <LockKeyhole />, title: "Controlled access", copy: "Agents issue report links intentionally, with expiry and revoke controls." }], note: "Crime information is never transformed into a safety verdict. Data remains source-, period-, and area-labelled." },
  "/agencies": { eyebrow: "For estate agencies", title: "A refined sales workspace that keeps the next move clear.", accent: "From listing to viewing", description: "Bring listing readiness, buyer enquiries, viewings, tasks, controlled shares and audit-aware exports into one organisation-scoped workflow.", primary: "Start an agency workspace", cards: [{ icon: <House />, title: "Structured listings", copy: "Create complete property records, manage image metadata, and make a public share only when it is ready." }, { icon: <ChartNoAxesCombined />, title: "Sales continuity", copy: "Keep leads, stages, viewing details and concise follow-up notes together." }, { icon: <Sparkles />, title: "Media, when configured", copy: "GenX jobs remain deployment-gated until the verified provider contract and credit controls are active." }], note: "Approved portal adapters are export-only. Amarktai does not scrape or post to third-party portals without written authorisation." },
  "/management": { eyebrow: "For property and complex managers", title: "Make the building work feel as considered as the front door.", accent: "Operational clarity at unit level", description: "Keep complex work connected: buildings, units, maintenance tickets, notices, visibility-aware documents, non-accounting levy activity, and resident scope.", primary: "Open management workspace", cards: [{ icon: <Building2 />, title: "Building register", copy: "Use buildings and units as the anchor for maintenance, resident assignment and notices." }, { icon: <ShieldCheck />, title: "Scoped residents", copy: "Accepted resident members can be assigned to units and see records limited to that unit and building." }, { icon: <FileCheck2 />, title: "Share with intention", copy: "Publish notices and managed documents only to their selected internal, owner, resident or public audience." }], note: "Operational levy entries are not represented as a full accounting ledger." },
  "/intelligence": { eyebrow: "Buyer intelligence", title: "Neighbourhood context with a provenance trail.", accent: "Context, not conjecture", description: "Amarktai separates what is known, where it came from, and when it was collected—so a buyer can ask better questions without receiving a misleading area verdict.", primary: "View report preview", cards: [{ icon: <MapPinned />, title: "Available map context", copy: "Reports are designed around spatial context and use visibly dated, source-aware layers." }, { icon: <BadgeCheck />, title: "Source-labelled claims", copy: "Crime and service material keep source, period and coverage visible at the point of use." }, { icon: <LockKeyhole />, title: "Controlled reports", copy: "Reports travel through revocable property-share links, not unbounded public pages." }], note: "Live amenity, service and crime layers activate only after the responsible licensed or approved source is configured." },
  "/security": { eyebrow: "Trust and security", title: "Confidence begins with boundaries that are real in the product.", accent: "Private by design", description: "Amarktai uses organisation memberships, role-specific actions, controlled shares, audit records and server-side payment verification to keep important workflows explicit.", primary: "Read trust & safety", cards: [{ icon: <LockKeyhole />, title: "Tenant boundaries", copy: "Every organisation-scoped mutation validates active membership on the server." }, { icon: <ShieldCheck />, title: "Controlled disclosure", copy: "Public property and buyer-report shares can expire, be revoked, and are unavailable by default." }, { icon: <FileCheck2 />, title: "Auditable operations", copy: "Critical actions—from exports to payment entitlements—can be retained as audit events." }], note: "Payment return pages never unlock access; only a verified PayFast notification can do that." },
  "/pricing": { eyebrow: "Transparent pricing", title: "Choose the operating room that matches your portfolio.", accent: "Clear plans. Verified entitlements.", description: "Start with a focused workspace and expand only when your listings, operational roles and media needs make it useful. Checkout is available only when PayFast is configured for the deployed domain.", primary: "Enter the workspace", cards: [{ icon: <House />, title: "Starter · R0", copy: "For a first workspace with core listings, reports and building operations." }, { icon: <Sparkles />, title: "Professional · R499 / month", copy: "For agency-ready workflows, team roles, exports and configured media credits." }, { icon: <UsersRound />, title: "Enterprise", copy: "For advanced access patterns and approved portal or integration requirements." }], note: "Paid entitlements are created only after an ITN-verified payment notification. There is no browser-return activation path." },
};

export default function PublicPage() {
  const [location] = useLocation();
  const page = pages[location] ?? pages["/platform"];
  const reportCta = location === "/buyers" || location === "/intelligence";
  useEffect(() => { document.title = `${page.eyebrow} | Amarktai Property`; let description = document.querySelector('meta[name="description"]') as HTMLMetaElement | null; if (!description) { description = document.createElement("meta"); description.name = "description"; document.head.appendChild(description); } description.content = page.description; }, [page]);
  return <div className="min-h-screen bg-[#faf9f6]"><PublicHeader /><main id="public-main" tabIndex={-1}><section className="relative overflow-hidden bg-[#17314e] pb-20 pt-24 text-white sm:pb-28 sm:pt-32"><div className="absolute inset-0 opacity-30"><div className="absolute -left-20 top-24 size-96 rounded-full bg-[#337f88] blur-3xl" /><div className="absolute -right-10 bottom-0 size-80 rounded-full bg-[#b68238] blur-3xl" /></div><div className="container relative max-w-5xl"><p className="eyebrow text-[#e5bf78]">{page.eyebrow}</p><h1 className="font-editorial mt-5 max-w-4xl text-5xl leading-[.98] sm:text-6xl lg:text-7xl">{page.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/75">{page.description}</p><div className="mt-9 flex flex-wrap gap-3">{reportCta ? <Link href="/report/preview" className="inline-flex items-center rounded-full bg-[#d9a856] px-6 py-3 text-sm font-bold text-[#193552] hover:bg-[#efc47d]">{page.primary}<ArrowRight className="ml-2 size-4" /></Link> : <Button onClick={() => startLogin()} className="rounded-full bg-[#d9a856] px-6 text-[#193552] hover:bg-[#efc47d]">{page.primary}<ArrowRight className="ml-2 size-4" /></Button>}<Link href="/security" className="inline-flex items-center rounded-full border border-white/30 px-6 py-3 text-sm font-semibold hover:bg-white/10">How Amarktai protects data</Link></div></div></section><section className="container py-18 sm:py-24"><div className="max-w-2xl"><p className="eyebrow">{page.accent}</p><p className="font-editorial mt-4 text-3xl leading-tight text-[#193552] sm:text-4xl">The product is intentional about what it can show, change and share.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{page.cards.map(card => <article key={card.title} className="soft-card min-h-56 p-7"><span className="grid size-11 place-items-center rounded-xl bg-[#edf2f1] text-[#193552]">{card.icon}</span><h2 className="mt-6 text-lg font-bold text-[#193552]">{card.title}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{card.copy}</p></article>)}</div><aside className="mt-10 rounded-[1.25rem] border border-[#d7e0d9] bg-[#eaf0ed] p-6 text-sm leading-7 text-[#315c5c]"><strong className="text-[#193552]">Amarktai standard:</strong> {page.note}</aside></section><section className="bg-white py-16"><div className="container flex flex-col justify-between gap-6 rounded-[1.5rem] bg-[#f1eee7] p-8 sm:p-10 md:flex-row md:items-center"><div><p className="eyebrow">A considered next step</p><h2 className="font-editorial mt-3 text-3xl text-[#193552]">Move from property information to a working system.</h2></div><Button onClick={() => startLogin()} className="shrink-0 rounded-full bg-[#193552] px-6 text-white hover:bg-[#264b6c]">Enter the workspace<ArrowRight className="ml-2 size-4" /></Button></div></section></main><PublicFooter /></div>;
}
