import { Building2, CircleCheck, Sparkles, Users, Zap } from 'lucide-react';

const planPaths = [
  { name: 'Individual', icon: Zap, description: 'A personal account path for individual spiritual practice and AI-assisted drafting after verified activation.' },
  { name: 'Family', icon: Users, description: 'A household-oriented subscription path. Final access rules and pricing are configured by the operator before launch.' },
  { name: 'Congregation', icon: Building2, description: 'A ministry-oriented subscription path. Administrative capabilities are activated only when the operator configures the relevant service scope.' },
];

export default function PricingSection() {
  return <section id="pricing" className="py-20 lg:py-32 px-4 sm:px-6 lg:px-8 bg-white"><div className="max-w-7xl mx-auto"><div className="text-center mb-16"><div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-[hsl(210,80%,95%)] text-[hsl(210,70%,50%)] text-sm font-medium mb-6"><Sparkles className="w-4 h-4" />Subscriptions</div><h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-slate-800">Subscription activation is <span className="text-gradient">configured before launch</span></h2><p className="mt-6 text-lg text-slate-600 max-w-2xl mx-auto">FaithHaven’s backend supports verified server-side checkout and subscription activation. Public prices, trial terms, feature entitlements, and availability are not published until the operator configures and validates the live payment catalog.</p></div><div className="grid md:grid-cols-3 gap-8">{planPaths.map((plan) => <article key={plan.name} className="bg-[hsl(48,60%,98%)] rounded-2xl p-8 border border-[hsl(48,30%,88%)]"><div className="w-14 h-14 rounded-xl bg-gradient-to-br from-[hsl(210,70%,60%)] to-[hsl(260,50%,65%)] flex items-center justify-center"><plan.icon className="w-7 h-7 text-white" /></div><h3 className="mt-6 text-xl font-bold text-slate-800">{plan.name}</h3><p className="mt-3 text-slate-600 leading-relaxed">{plan.description}</p><div className="mt-6 flex items-center gap-2 text-sm text-slate-500"><CircleCheck className="w-4 h-4 text-[hsl(150,30%,45%)]" />Server-side activation required</div></article>)}</div><p className="mt-12 text-center text-sm text-slate-500">Do not enter payment details until the live PayFast checkout, merchant identity, subscription terms, and return/cancel pages have been configured and verified by the operator.</p></div></section>;
}
