import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Database, MapPinned, RefreshCw, ShieldCheck } from "lucide-react";
import { useState } from "react";

type PropertyOption = { id: number; title: string; addressLine: string };

export function BuyerIntelligenceSourcePanel({ organisationId, properties, canManage }: { organisationId?: number; properties: PropertyOption[]; canManage: boolean }) {
  const utils = trpc.useUtils();
  const sources = trpc.amenity.sources.useQuery(undefined, { staleTime: 60_000 });
  const refresh = trpc.amenity.refresh.useMutation({ onSuccess: () => utils.platform.snapshot.invalidate() });
  const [sourcePath, setSourcePath] = useState<"public_osm" | "licensed_provider">("public_osm");
  const [propertyId, setPropertyId] = useState("");
  const [result, setResult] = useState<{ cached: boolean; amenityCount: number; validUntil: Date } | null>(null);
  const publicSource = sources.data?.public;
  const licensedSource = sources.data?.licensed;
  const selected = sourcePath === "public_osm" ? publicSource : licensedSource;
  const canRunPublic = canManage && Boolean(propertyId) && sourcePath === "public_osm";

  return <section className="dashboard-card mt-5">
    <div className="flex flex-col gap-3 border-b border-[#e7e1d8] pb-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="eyebrow">Buyer-intelligence data path</p><h2 className="font-editorial mt-2 text-3xl text-[#193552]">Choose how amenity evidence is sourced.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">The public path is a bounded, user-triggered lookup that records its source and retrieval date. The licensed path stays visible but sends nothing until its deployment contract is complete.</p></div><span className="inline-flex w-fit items-center rounded-full bg-[#edf5ef] px-3 py-1 text-xs font-bold text-[#337f88]"><ShieldCheck className="mr-1.5 size-3.5" />Server-mediated</span></div>
    <div className="mt-5 grid gap-4 lg:grid-cols-[1fr_.9fr]"><div className="grid gap-3"><label className="grid gap-1.5 text-sm font-semibold text-[#193552]">Source path<select value={sourcePath} onChange={event => { setSourcePath(event.target.value as typeof sourcePath); setResult(null); }} className="h-10 rounded-md border border-input bg-white px-3 text-sm"><option value="public_osm">Public mapped amenities</option><option value="licensed_provider">Licensed data provider</option></select></label><label className="grid gap-1.5 text-sm font-semibold text-[#193552]">Property<select value={propertyId} onChange={event => setPropertyId(event.target.value)} disabled={!canManage || !properties.length} className="h-10 rounded-md border border-input bg-white px-3 text-sm"><option value="">Select a property</option>{properties.map(property => <option key={property.id} value={property.id}>{property.title} · {property.addressLine}</option>)}</select></label><Button disabled={!canRunPublic || refresh.isPending} onClick={() => refresh.mutate({ organisationId, propertyId: Number(propertyId), sourcePath }, { onSuccess: response => setResult(response) })} className="w-fit rounded-full bg-[#193552] hover:bg-[#264b6c]"><RefreshCw className={`mr-2 size-4 ${refresh.isPending ? "animate-spin" : ""}`} />{refresh.isPending ? "Refreshing evidence…" : "Refresh public amenities"}</Button>{!canManage && <p className="text-xs leading-5 text-slate-500">Your membership can view intelligence but cannot refresh report evidence.</p>}{refresh.error && <p className="text-sm text-red-700">{refresh.error.message}</p>}</div><aside className="rounded-2xl border border-[#dbe5de] bg-[#f8fbf8] p-5"><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-lg bg-white text-[#337f88]">{sourcePath === "public_osm" ? <MapPinned className="size-4" /> : <Database className="size-4" />}</span><p className="text-sm font-bold text-[#193552]">{selected?.label ?? "Loading source status…"}</p></div><p className="mt-3 text-sm leading-6 text-slate-600">{selected?.detail}</p>{sourcePath === "public_osm" ? <p className="mt-4 text-xs leading-5 text-slate-500">The request runs only after you press refresh. It caches the selected property result for 24 hours, includes OpenStreetMap provenance, and is not an area-quality or safety score.</p> : <p className="mt-4 text-xs leading-5 text-[#9a691f]">{licensedSource?.ready ? "The provider is configured, but approved response mapping still needs activation." : "No provider name, endpoint, or secret is exposed here. Configure all three only at deployment."}</p>}{result && <div className="mt-4 rounded-xl border border-[#cfe0d4] bg-white p-3 text-xs text-[#315c5c]"><p className="font-bold">{result.cached ? "Using the existing cached result" : "Public amenity evidence refreshed"}</p><p className="mt-1">{result.amenityCount} mapped places · valid until {new Date(result.validUntil).toLocaleString()}</p></div>}</aside></div>
  </section>;
}
