import React from "react";
import { BadgeCheck, ExternalLink } from "lucide-react";
import { trpc } from "@/lib/trpc";

type Source = { label?: string; url?: string; retrievedAt?: string; coverage?: string; period?: string };
type EvidenceSnapshot = { sources?: Source[]; geographicScope?: string; generatedAt?: string };
type ResultSnapshot = { summary?: string; caveats?: string };

export function ResearchEvidenceList({ organisationId }: { organisationId?: number }) {
  const status = trpc.research.status.useQuery({ organisationId }, { enabled: Boolean(organisationId) });
  const completed = (status.data?.jobs ?? []).filter(job => job.status === "completed");
  if (status.isLoading) return <section className="dashboard-card mt-5" aria-busy="true"><p className="text-sm font-semibold text-[#193552]">Loading source-reviewed evidence…</p><p className="mt-1 text-xs text-slate-500">Completed results remain unavailable until the tenant-scoped evidence record has loaded.</p></section>;
  if (status.error) return <section className="dashboard-card mt-5 border-red-200 bg-red-50" role="alert"><p className="text-sm font-semibold text-red-800">Source-reviewed evidence could not be loaded.</p><p className="mt-1 text-xs text-red-700">Refresh the workspace to retry. No provider draft or unreviewed result is shown as a fallback.</p></section>;
  return <section className="dashboard-card mt-5"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#edf5ef] text-[#337f88]"><BadgeCheck className="size-4" /></span><div><p className="text-sm font-bold text-[#193552]">Completed source-reviewed evidence</p><p className="text-xs text-slate-500">Only immutable, attributable results appear here. Provider drafts and unreviewed claims are not displayed.</p></div></div>{completed.length ? <div className="mt-4 space-y-3">{completed.map(job => { const snapshot = job.sourceSnapshot as EvidenceSnapshot | null; const result = job.resultSnapshot as ResultSnapshot | null; const sources = snapshot?.sources?.filter(source => source.label && source.url && source.retrievedAt && source.coverage) ?? []; return <article key={job.id} className="rounded-xl border border-[#dbe5de] bg-[#f6faf7] p-4"><div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between"><p className="font-bold text-[#193552]">{job.researchType} · {snapshot?.geographicScope ?? job.locationLabel}</p><p className="text-xs font-semibold text-[#337f88]">Reviewed {snapshot?.generatedAt ? new Date(snapshot.generatedAt).toLocaleDateString() : job.completedAt ? new Date(job.completedAt).toLocaleDateString() : "date unavailable"}</p></div>{result?.summary && <p className="mt-3 text-sm leading-6 text-slate-700">{result.summary}</p>}{result?.caveats && <p className="mt-2 text-xs leading-5 text-slate-600"><strong>Caveat:</strong> {result.caveats}</p>}<div className="mt-3 space-y-1 text-xs leading-5 text-slate-600">{sources.map((source, index) => <p key={`${source.url}-${index}`}><a href={source.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 font-semibold text-[#315c5c] underline underline-offset-2">{source.label}<ExternalLink className="size-3" /></a> · retrieved {new Date(source.retrievedAt!).toLocaleDateString()} · {source.coverage}{source.period ? ` · period ${source.period}` : ""}</p>)}</div></article>; })}</div> : <p className="mt-4 rounded-xl border border-dashed border-[#dedbd3] p-3 text-sm text-slate-500">No source-reviewed research is complete yet. Queue a guarded request, then record the verified sources through the review workflow.</p>}</section>;
}
